/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaSwitch;

public class Library {
    public boolean weekday(Day d) {
        boolean ret = false;
        switch (d)
        {
            case MONDAY:
                ret = true;
                break;
            case TUESDAY:
                ret = true;
                break;
            case WEDNESDAY:
                ret = true;
                break;
            case THURSDAY:
                ret = true;
                break;
            case FRIDAY:
                ret = true;
                break;
            case SATURDAY:
                ret = false;
                 break;
            case SUNDAY:
                ret = false;
                break;
            default:
                ret = false;
                break;
        }
        return ret;
    }
}
